# Reload config with r
unbind r
bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

# General settings
set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g mouse on
set-option -g status-position top

# Fix color issues
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'TechnicalDC/tmux-pywal-theme'
set -g @pywal_widgets "#(date +%s)"
set -g @pywal_time_format "%I:%M %p"

run '~/.tmux/plugins/tpm/tpm'

