general {
    layout = dwindle
}


dwindle {
  pseudotile = false
  preserve_split = true
  smart_resizing = true
  permanent_direction_override = true
  split_width_multiplier = 0
  split_bias = 1
}
