


source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animation.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf




