foreground         #c1c2c3
background         #070B10
background_opacity 1.0
cursor             #c1c2c3

active_tab_foreground     #070B10
active_tab_background     #c1c2c3
inactive_tab_foreground   #c1c2c3
inactive_tab_background   #070B10

active_border_color   #c1c2c3
inactive_border_color #070B10
bell_border_color     #2E4558

color0       #070B10
color8       #565f69
color1       #2E4558
color9       #2E4558
color2       #204D63
color10      #204D63
color3       #5D4D64
color11      #5D4D64
color4       #4E516C
color12      #4E516C
color5       #A08361
color13      #A08361
color6       #3C67A1
color14      #3C67A1
color7       #c1c2c3
color15      #c1c2c3
