foreground         #c1c1c1
background         #0a070a
background_opacity 1.0
cursor             #c1c1c1

active_tab_foreground     #0a070a
active_tab_background     #c1c1c1
inactive_tab_foreground   #c1c1c1
inactive_tab_background   #0a070a

active_border_color   #c1c1c1
inactive_border_color #0a070a
bell_border_color     #473254

color0       #0a070a
color8       #675467
color1       #473254
color9       #473254
color2       #4E356E
color10      #4E356E
color3       #664C6D
color11      #664C6D
color4       #583D84
color12      #583D84
color5       #6B5192
color13      #6B5192
color6       #9263AB
color14      #9263AB
color7       #c1c1c1
color15      #c1c1c1
