exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = swww-daemon &
exec-once = $system
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/flames/scripts/battery-charging.sh
exec-once = $dock
exec-once = hyprshell run &
exec-once = hypridle &
exec-once = hyprpm enable hyprexpo
exec-once = flatpak override --filesystem=~/.themes:ro --filesystem=~/.icons:ro --user
exec-once = hyprctl setcursor Imouto 24
