source = /home/aislx/.config/hypr/conf/monitors/1440x1080.conf
source = /home/aislx/.config/hypr/conf/monitors/1920x1080.conf
source = /home/aislx/.config/hypr/conf/monitors/default.conf
source = /home/aislx/.config/hypr/conf/monitors/3440x1440.conf
source = /home/aislx/.config/hypr/conf/monitors/default.conf
source = ~/.config/hypr/conf/monitors/default.conf
