$terminal = kitty
$fileManager = thunar
$launcher = ~/.config/rofi/launcher-theme.sh
$launcherswitcher = ~/.config/rofi/launcher-switcher.sh
$powermenu = ~/.config/rofi/powermenu-theme.sh
$powermenuswitcher = ~/.config/rofi/powermenu-switcher.sh
