$terminal = kitty
$fileManager = nautilus
$wallpaper = ~/.local/bin/wallch
$launcher = ~/.config/flames/scripts/applauncher.sh
$launcherswitcher = ~/.config/flames/scripts/launcher-theme-switcher.sh
$powermenu = ~/.config/flames/scripts/powermenu.sh
$powermenuswitcher = ~/.config/rofi/powermenu-switcher.sh
$lockscreen = hyprlock &
$dock = ~/.config/nwg-dock-hyprland/launch.sh
$system = ~/.config/flames/scripts/sysreload.sh
$settings = cd ~/.config/asirahub/ && ./menu.sh
$focus = ~/.config/flames/scripts/focus-mode.sh
$toggle_waybar = ~/.config/hypr/scripts/toggle-waybar.sh
$screenshot = ~/.config/rofi/screenshot.sh
