windowrulev2 = float, class:.* 
windowrule = animation popin, class:^(kitty)$
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = opacity 0.8 0.8, class:^(rofi)$
windowrule = opacity 0.8 0.8, class:^(waybar)$
layerrule = blur, rofi
layerrule = blur, waybar
layerrule = blur, nwg-dock-hyprland
windowrule = opacity 0.8 0.8, class:^(nwg-dock-hyprland)$
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev2 = opacity 1.0 1.0, title:^(ScreenshotFreeze)$
windowrulev2 = fullscreen, title:^(ScreenshotFreeze)$
windowrulev2 = nofocus, title:^(ScreenshotFreeze)$
windowrulev2 = float, title:^(ScreenshotFreeze)$
windowrulev2 = stayfocused, title:^(ScreenshotFreeze)$
windowrulev2 = noanim, title:^(ScreenshotFreeze)$


