# -----------------------------------------------------
# Window rules
# -----------------------------------------------------


windowrule = animation slide bottom, match:class .*
windowrule = animation slide top, match:class .*kitty.*

windowrule = opacity 0.9 0.9, match:class .*nemo.*
windowrule = opacity 0.9 0.9, match:class .*Rofi.*

windowrule = suppress_event maximize, match:class .*
# windowrule = no_focus on,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = opacity 0.8 0.8, match:class .*rofi.*
windowrule = opacity 0.8 0.8, match:class .*waybar.*
layerrule = blur on, match:namespace rofi
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace nwg-dock-hyprland
layerrule = blur on, ignore_alpha 0, xray 0, animation slidefade top 90%, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0, xray 0, match:namespace swaync-notification-window
windowrule = opacity 0.8 0.8, match:class .*nwg-dock-hyprland.*

windowrule = opacity 1.0 1.0, match:title .*ScreenshotFreeze.*
windowrule = fullscreen on, match:title .*ScreenshotFreeze.*
windowrule = no_focus on, match:title .*ScreenshotFreeze.*
windowrule = float on, match:title .*ScreenshotFreeze.*
windowrule = stay_focused on, match:title .*ScreenshotFreeze.*
windowrule = no_anim on, match:title .*ScreenshotFreeze.*
 
# Browser right click blur fix
# windowrule = no_blur on, match:class .*.*, title: .*.*


windowrule = tile on, match:title .*Microsoft-edge.*
windowrule = tile on, match:title .*Brave-browser.*
windowrule = tile on, match:title .*Chromium.*
windowrule = float on, match:title .*pavucontrol.*
windowrule = float on, match:title .*blueman-manager.*
windowrule = float on, match:title .*nm-connection-editor.*
windowrule = float on, match:title .*qalculate-gtk.*

# Browser Picture in Picture
windowrule = float on, match:title .*Picture-in-Picture.*
windowrule = pin on, match:title .*Picture-in-Picture.*
windowrule = move 69.5% 4%, match:title .*Picture-in-Picture.*
