# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = float on, match:class .*
windowrule = animation slide bottom, match:class .*
windowrule = animation slide top, match:class .*kitty.*

windowrule = opacity 0.9 0.9, match:class .*kitty.*
windowrule = opacity 0.9 0.9, match:class .*nemo.*
windowrule = opacity 0.9 0.9, match:class .*Rofi.*

windowrulev2 = suppressevent maximize, match:class .*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = opacity 0.8 0.8, match:class .*rofi.*
windowrule = opacity 0.8 0.8, match:class .*waybar.*
layerrule = blur on, match:namespace rofi
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace nwg-dock-hyprland
windowrule = opacity 0.8 0.8, match:class .*nwg-dock-hyprland.*

windowrulev2 = opacity 1.0 1.0, match:title .*ScreenshotFreeze.*
windowrulev2 = fullscreen, match:title .*ScreenshotFreeze.*
windowrulev2 = nofocus, match:title .*ScreenshotFreeze.*
windowrulev2 = float, match:title .*ScreenshotFreeze.*
windowrulev2 = stayfocused, match:title .*ScreenshotFreeze.*
windowrulev2 = noanim, match:title .*ScreenshotFreeze.*

# Browser right click blur fix
windowrulev2 = noblur, match:class .*.*, title:^()$


windowrule = tile on, match:title .*Microsoft-edge.*
windowrule = tile on, match:title .*Brave-browser.*
windowrule = tile on, match:title .*Chromium.*
windowrule = float on, match:title .*pavucontrol.*
windowrule = float on, match:title .*blueman-manager.*
windowrule = float on, match:title .*nm-connection-editor.*
windowrule = float on, match:title .*qalculate-gtk.*

# Browser Picture in Picture
windowrule = float on, match:title .*Picture-in-Picture.*
windowrule = pin on, match:title .*Picture-in-Picture.*
windowrule = move 69.5% 4%, match:title .*Picture-in-Picture.*
